import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-imagens',
  templateUrl: './imagens.component.html',
  styleUrls: ['./imagens.component.css'],
})
export class ImagensComponent implements OnInit {
  imagemValeria: string = './assets/images/Valeria.png';
  imagemCesar: string = './assets/images/Cesar.png';
  imagemMirelly: string = './assets/images/Mirelly.png';
  imagemSuzane: string = './assets/images/Suzane.png';
  imagemEzequiel: string = './assets/images/Ezequiel.png';
  imagemKarol: string = './assets/images/Karol.png';
  imagemWillian: string = './assets/images/Willian.png';
  imagemVictor: string = './assets/images/Victor2.png';
  imagemIvan: string = './assets/images/Ivan.png';
  imagemAkin: string = './assets/images/Akin.png';
  imagemDaniel: string = './assets/images/Daniel.png';
  imagemHudson: string = './assets/images/Hudson.png';
  imagemGustavo: string = './assets/images/Gustavo.png';
  imagemCintia: string = './assets/images/Cintia.png';
  imagemMariana: string = './assets/images/Mariana.png';
  imagemMarcos: string = './assets/images/Marcos.png';
  imagemNatalia: string = './assets/images/Natalia.png';

  texto_Valeria1: string =
    'Valéria, que já foi uma implacável assassina da Tríplice conhecida por "vigilante fantasma", agora vive em reclusão fora dos limites da cidade, em um antigo zoológico abandonado. Após se afastar da organização, ela passou duas décadas vivendo em isolamento e solidão. Durante esse período, Valéria desenvolveu um laço incomum com lobos, compartilhando seu espaço e vivendo entre esses animais selvagens. Proibida de se alimentar dentro dos limites da capital, Valéria vive em uma realidade complexa, lutando contra seus instintos vampíricos enquanto tenta controlar sua sede de sangue. Essa restrição a afastou ainda mais da civilização e a levou a uma vida de autoimposto exílio e isolamento.';
  texto_Valeria2: string =
    'Conhecida por sua impaciência e por lidar mal com as pessoas, Valéria foi apelidada pelos membros da Tríplice de "bomba-relógio". Entretanto, para aqueles que ouviam falar de suas façanhas como assassina, ela era conhecida como o "vigilante fantasma". Seu estilo de assassinato meticuloso e habilidade em eliminar alvos sem deixar rastros a transformaram em uma lenda urbana, deixando tanto criminosos quanto autoridades perplexos e temerosos. Apesar de seu passado sangrento, Valéria encontrou um tipo de paz na companhia dos lobos. Esses animais selvagens, com sua natureza livre e instintos primitivos, ofereceram a ela uma conexão única com a natureza e uma chance de redenção. Entre os lobos, Valéria encontrou uma espécie de compreensão e aceitação que ela nunca experimentou com os humanos, estabelecendo uma profunda conexão com a natureza selvagem que a rodeia. Ao longo dos anos, Valéria tem lutado com seu passado sangrento e suas ações como assassina. Seu desejo por redenção e a busca por uma vida mais significativa são contraditos pelo peso das vidas que ela ceifou em nome da Tríplice. Ela se sente aprisionada em um ciclo de culpa e arrependimento, uma sombra do que costumava ser. Enquanto Valéria tenta encontrar paz em sua reclusão e entre os lobos, o mundo ao seu redor continua a ser moldado pelas intrigas e disputas da Tríplice. Eventos do passado e do presente continuam a influenciar sua jornada, e ela se vê envolvida novamente nos assuntos da organização que um dia foi sua casa. À medida que a história avança, os leitores são convidados a explorar os dilemas e conflitos internos de Valéria, acompanhando sua jornada de redescoberta e possível redenção. Sua personalidade complexa e sua ligação com os lobos prometem acrescentar camadas intrigantes à narrativa, enquanto ela enfrenta os desafios de seu passado e tenta encontrar um propósito em meio ao caos que a cerca.';

  texto_Mirelly1: string =
    'Tanto temida quanto respeitada, a Srta M é a líder sombria da Tríplice, exercendo um controle absoluto sobre a cidade com seus métodos e habilidades excepcionais. Ela manipula os eventos na cidade, garantindo que a criminalidade ocorra apenas sob seus termos e conhecimento, impedindo que crimes aconteçam sem sua ciência. Os criminosos sabem que violar suas regras resultará em terríveis consequências, o que torna sua figura uma espécie de entidade sobrenatural, por aqueles que ousam desafiar sua autoridade.';
  texto_Mirelly2: string =
    'Conhecida apenas por seu codinome, a Srta M se esconde por trás da fachada de uma influente e bem-sucedida empresária. Como proprietária da renomada empresa funerária Mortisman, Mirelly utiliza esse disfarce para se mover na sociedade. Sua presença tenebrosa lança uma sombra sobre a cidade, enquanto ela impõe suas regras e conduz seus planos obscuros, tecendo uma teia complexa de influência e poder. Governa com mão de ferro, exercendo um controle meticuloso sobre a cidade. Apesar de suas ações rigorosas, a Srta M é uma personagem complexa, com nuances de moralidade e um senso peculiar de justiça. Sua presença inspira fascínio e medo naqueles que a cercam. Sob sua liderança, a Tríplice se tornou uma força dominante, controlando a ordem nas sombras da cidade, ao mesmo tempo em que gera questionamentos sobre a natureza da justiça e o verdadeiro funcionamento da própria cidade em que ela reina. À medida que a história se desenrola, os leitores são convidados a desvendar os mistérios por trás das motivações da Srta M. Enquanto a cidade enfrenta o caos e a criminalidade, ela permanece como a sombra que protege e governa, envolta em segredos e motivos desconhecidos. Prepare-se para mergulhar nas profundezas da mente da Srta M e descobrir até onde ela está disposta a ir para manter seu domínio sobre a cidade e todos que se atrevem a desafiá-la.';

  texto_Cesar1: string =
    'Vivendo em seu escritório no centro da cidade, César é um vampiro feio e deformado. Sua aparência assustadora é caracterizada por dentes afiados e uma pele pálida. Apesar disso, ele se veste de maneira elegante, preferindo roupas antiquadas que complementam sua personalidade distinta. Ele é um ser enigmático e persuasivo. Sua lábia refinada e inteligência fora do comum fazem dele um mestre na arte da persuasão. Sua presença bizarra e carismática atrai tanto clientes dispostos a pagar o alto preço exigido por seus serviços de ocultismo quanto subordinados que desejam fazer parte de seu círculo interno.';
  texto_Cesar2: string =
    'Além de suas habilidades persuasivas, César é reconhecido por sua expertise em ocultismo. Ele possui conhecimentos extraordinários e é capaz de prever o futuro, fornecendo informações valiosas aos clientes que buscam seus serviços. Sua capacidade de se ocultar no meio da multidão, sem precisar realmente se esconder, confere-lhe uma vantagem significativa, tornando-o quase indetectável. Ele é acompanhado por uma equipe leal: um guarda-costas e porteiro, responsável por sua segurança e pela filtragem de visitantes indesejados, e três criminosos negociantes, cada um especializado em suas próprias áreas. Esses colaboradores ajudam César a gerenciar seus negócios e a realizar atividades relacionadas a seus clientes Dentro da Tríplice, o vampiro desempenha um papel crucial. Seus conhecimentos ocultos e habilidades especiais fornecem uma vantagem estratégica para a organização. Sua habilidade em prever o futuro e sua capacidade de se mover nas sombras tornam-no uma peça valiosa no jogo de poder da Tríplice. Com o desenrolar da história, os leitores são convidados a descobrir mais sobre as verdadeiras motivações de César, seu papel dentro da Tríplice e como ele manipula os eventos por trás da fachada elegante e sinistra de seu escritório. Sua presença enigmática e suas habilidades extraordinárias certamente trarão mistério e intriga à narrativa, enquanto se desvenda seus planos obscuros.';

  texto_Suzane1: string =
    'Suzane, a mais velha dentre os membros da Tríplice, é uma vampira vingativa, perigosa e imprevisível. Seu passado é envolto em mistério, pois ao longo da história da humanidade, ela assumiu várias identidades, mas é conhecida entre os vampiros como "A Bruxa". Sua reputação vem de sua profunda compreensão da ciência, o que lhe confere um ar sobrenatural, tornando-se uma das vampiras mais enigmáticas do grupo. Suzane carrega consigo séculos de conhecimento e experiência.';
  texto_Suzane2: string =
    'Seu domínio na ciência não é sobrenatural, mas sim resultado de suas habilidades e conhecimentos extraordinários. Sua compreensão profunda da ciência e da natureza humana lhe confere uma vantagem única, permitindo que ela manipule eventos de forma inteligente e calculada. Além de sua imortalidade e poderes vampíricos, Suzane possui dois "filhos da noite". Sua relação com esses vampiros é complexa, oscilando entre ser protetora e maternal, e ao mesmo tempo, mantendo uma forte influência sobre eles, orientando-os em sua existência eterna. Suzane é uma mestra em esconder seus verdadeiros poderes, preferindo mantê-los ocultos e surpreender seus inimigos com suas capacidades imprevisíveis. Sua natureza vingativa é alimentada por acontecimentos do passado, que a levaram a se tornar uma figura implacável e sedenta de vingança. Dentro da Tríplice, Suzane é uma das figuras mais antigas e respeitadas, com uma influência significativa sobre o destino da organização. Sua boate em formato de castelo medieval é o epicentro de suas operações, onde ela fornece entretenimento adulto para os humanos e comanda sua corte de seguidores, manipulando eventos para atender a seus próprios objetivos. A história desenrola-se em meio ao mistério e às revelações sobre as várias identidades que Suzane adotou ao longo dos séculos e os motivos que a impulsionam. Enquanto a cidade enfrenta os desafios impostos pela Tríplice, Suzane permanece como uma figura enigmática, envolta em segredos e intrigas. Prepare-se para conhecer as personalidades que ela já assumiu e tudo que ela é capaz de fazer por vingança, em uma jornada repleta de descobertas e revelações surpreendentes.';

  texto_Willian1: string =
    'Braço direito da temida Srta M, William é um homem obcecado em se tornar um vampiro. Sua determinação o leva a trabalhar incansavelmente para alcançar esse objetivo, tornando-se uma figura intrigante e ambiciosa dentro da Tríplice. Anteriormente, William era membro da equipe de extermínio liderada por Valéria, desempenhando o papel de um exímio atirador. Sua habilidade de mira e precisão com as armas o torna um membro valioso da organização, capaz de eliminar inimigos com eficiência e sem hesitação. Apesar de suas habilidades notáveis, William é conhecido por sua frieza emocional. Ele raramente demonstra emoções em suas expressões, falas e gestos, mantendo-se sempre calmo e imperturbável, o que o torna ainda mais obscuro e intimidador.';
  texto_Willian2: string =
    'O desejo de se tornar um vampiro é o que o impulsiona. Ele acredita que, ao se juntar à raça vampírica, obterá ainda mais poder e, assim, alcançará a respeitada posição que almeja na Tríplice. Essa ambição, no entanto, o coloca em um caminho perigoso, onde ele pode ter que enfrentar consequências imprevistas de suas ações.Dentro da Tríplice, William é reconhecido como um homem de confiança da Srta M, cumprindo suas ordens com zelo e lealdade. Sua presença silenciosa e eficaz atrai respeito dos outros membros, mas também um certo temor, já que poucos conseguem decifrar suas verdadeiras intenções e desejos. À medida que a história avança, os leitores são levados a descobrir mais sobre os motivos e a jornada pessoal de William. Enquanto ele continua sua busca para se tornar um vampiro e ascender na hierarquia da Tríplice, os dilemas e conflitos internos o colocam em uma encruzilhada, questionando a verdadeira natureza de seus desejos e os limites que está disposto a ultrapassar. Prepare-se para se aprofundar na mente reservada e implacável de William, enquanto ele navega pelas intrigas e perigos que envolvem a Tríplice e sua obsessão por se tornar um vampiro, em uma jornada de autodescoberta e decisões cruciais que moldarão o destino da organização e de si mesmo.';

  texto_Victor1: string =
    'Victor é um homem enigmático que veio do exterior para a capital com um objetivo ambicioso: assumir o papel de seu falecido irmão como líder do tráfico de drogas da zona leste. No entanto, em vez de seguir as leis e normas estabelecidas pela temida Srta M e sua Tríplice, ele desencadeia uma onda de violência pela cidade, decidindo tomar o controle absoluto da capital. Seu caráter implacável e determinação em alcançar seu objetivo fizeram dele um rival perigoso para Mirelly, a líder da Tríplice. Victor não recuou diante das várias tentativas da organização de eliminá-lo, demonstrando habilidades e astúcia impressionantes que o permitiram sobreviver e manter-se como uma ameaça constante.';
  texto_Victor2: string =
    'Em seu caminho rumo ao poder, Victor atraiu seguidores leais, formando uma gangue temida que o ajuda a impor sua vontade pela cidade. Sua personalidade magnética e discurso convincente lhe garantiram uma base de apoio crescente entre os criminosos descontentes e oprimidos, tornando-se uma figura carismática para aqueles que buscam mudanças na cidade.Confrontando a Srta M e a Tríplice, Victor é visto como um rebelde, desafiando as normas estabelecidas e ameaçando o status quo. Sua ambição de tomar o controle da capital o coloca em rota de colisão direta com Mirelly, gerando um conflito intenso entre eles.À medida que a história avança, os leitores são levados a mergulhar nas motivações de Victor e nas circunstâncias que o levaram a buscar poder e vingança na capital. Enquanto ele luta para conquistar a cidade, enfrentando a feroz resistência da Tríplice e sua líder, sua jornada se torna uma narrativa emocionante e repleta de reviravoltas.Prepare-se para testemunhar o embates entre Victor e Mirelly, enquanto ele desafia a hierarquia estabelecida, questionando a própria natureza da liderança e os limites da ambição humana. A história promete desvendar os segredos e mistérios por trás do caminho sangrento que Victor trilhou em sua ascensão ao poder, criando um cenário de confronto épico na luta pelo controle da capital.';

  texto_Ivan1: string =
    'Ivan foi trazido do exterior por Victor para auxiliá-lo em sua missão de conquistar a cidade. Tornando-se um aliado formidável para o ambicioso líder do tráfico. Sob a alcunha de "Vigilante Fantasma", Ivan assume involuntariamente o título que um dia pertenceu a Valéria. Essa coincidência intrigante acaba por aumentar sua reputação. Ivan é conhecido por fazer tudo com as próprias mãos, preferindo resolver os problemas de forma direta e incisiva. Sua habilidade em lidar com adversários de forma brutal o torna um executor eficiente.';

  texto_Ivan: string =
    'Ivan é um homem de origens desconhecidas, trazido do exterior por Victor para auxiliá-lo em sua missão de conquistar a cidade. Sua presença enigmática e aura de mistério o tornam um aliado formidável para o ambicioso líder do tráfico. A imponência de Ivan é marcada por sua extrema força e natureza violenta, características que o tornam uma figura temida e respeitada dentro da gangue liderada por Victor. Sob a alcunha de "Vigilante Fantasma", Ivan assume involuntariamente o título que um dia pertenceu a Valéria, uma figura proeminente do passado da cidade. Essa coincidência intrigante acaba por aumentar sua reputação, alimentando ainda mais o mistério que o envolve. Ivan é conhecido por fazer tudo com as próprias mãos, preferindo resolver os problemas de forma direta e incisiva. Sua habilidade em lidar com adversários de forma brutal o torna um executor eficiente das ordens de Victor, e ele não hesita em enfrentar desafios que surgem em seu caminho. A relação entre Ivan e Victor é construída sobre uma parceria profunda e sombria. À medida que a história se desenrola, os leitores são convidados a desvendar o passado e os segredos por trás de Ivan e sua conexão com Victor. O mistério em torno de seu passado, suas motivações e a relação com o título de "Vigilante Fantasma" lançam uma sombra de intriga sobre o enredo.Prepare-se para se envolver em uma narrativa que revela a verdadeira natureza de Ivan e os laços que o unem a Victor. Enquanto a cidade se vê envolvida em um conflito entre facções poderosas, o papel enigmático de Ivan como o "Vigilante Fantasma" acrescenta uma camada adicional de complexidade à trama, garantindo uma história repleta de ação, suspense e revelações surpreendentes.';

  texto_Akin_Isaac1: string =
    'Akin e Isaac são os homens de confiança de Victor. Com histórias distintas e origens em países diferentes, eles trazem habilidades únicas para a equipe. Sua dedicação ao líder do tráfico é inabalável, e eles estão dispostos a arriscar suas vidas para garantir o sucesso de seus planos. Dentro da equipe, Akin e Isaac se destacam como homens de ação, prontos para cumprir as ordens do líder e agir com eficiência para garantir sua proteção e sucesso. A presença deles promete surpreender ao revelar segredos, quando se mostram peças importantes no jogo mortal que se desenrola na luta pelo controle da capital.';

  texto_Akin_Isaac2: string =
    'Akin e Isaac são os homens de confiança de Victor, desempenhando um papel crucial em sua missão de conquistar a cidade e consolidar seu domínio. Com histórias distintas e origens em países diferentes, eles trazem habilidades únicas para a equipe de Victor. Akin, é um indivíduo habilidoso e furtivo. Em seu passado, ele trabalhou como guarda-costas para celebridades, ganhando experiência em proteção e vigilância. Sua capacidade de se mover silenciosamente nas sombras o torna um ativo valioso para Victor, permitindo que ele execute planos com eficiência e proteja seu líder de possíveis atentados à sua vida. Já Isaac, traz consigo uma força impressionante e uma presença imponente. A força bruta de Isaac é um complemento perfeito para as habilidades mais furtivas de Akin, garantindo a Victor uma dupla de confiança capaz de enfrentar diversos desafios. Akin e Isaac são leais a Victor, seguindo suas ordens sem questionamentos. A relação entre eles é marcada por um respeito mútuo e uma camaradagem forjada por batalhas compartilhadas e um propósito comum. Sua dedicação ao líder do tráfico é inabalável, e eles estão dispostos a arriscar suas vidas para garantir o sucesso de seus planos. Dentro da equipe de Victor, Akin e Isaac se destacam como homens de ação, prontos para cumprir as ordens do líder e agir com eficiência para garantir sua proteção e sucesso. À medida que a história se desenrola, os leitores são convidados a conhecer mais sobre natureza deles e os eventos que os levaram a se juntar a Victor em sua busca pelo poder na cidade. A trama promete surpreender ao revelar seus segredos, enquanto eles continuam a ser peças-chave no jogo mortal que se desenrola na luta pelo controle da capital.';

  texto_Karol1: string =
    'Karol, a filha da noite de Suzane, reside no castelo de sua mãe, onde aprende as habilidades e conhecimentos da linhagem vampírica. Como novos vampiros são proibidos na cidade, Karol é mantida reclusa no castelo. Karol é uma satanista fervorosa, incorporando elementos sombrios em sua vida e vestindo-se de freira, em um contraste provocativo entre o sagrado e o profano.';
  texto_Karol2: string =
    'Sua aparência sedutora esconde um instinto predatório e uma determinação implacável para servir e agradar a sua mãe vampira, Suzane. Como discípula, Karol é leal e disposta a fazer qualquer coisa para proteger e agradar Suzane. Sua devoção é profunda, e ela considera sua mãe da noite uma figura divina, seguindo seus ensinamentos com devoção religiosa. O vínculo entre elas é tanto de amor quanto de submissão, e Karol está disposta a sacrificar tudo em nome de sua família vampírica.';

  texto_Ezequiel1: string =
    'Como braço direito e filho da noite de Suzane, o atraente vampiro vive dentro dos limites do castelo de sua mãe. Sua presença lá dentro é indispensável, pois além de administrar as atividades do lugar, ele atua como os olhos e ouvidos de Suzane, identificando possíveis ameaças e protegendo sua mãe da noite de qualquer perigo que se aproxime.';
  texto_Ezequiel2: string =
    'Belo e chermoso, ele atrai os olhares e corações dos que o cercam, tornando-se um sedutor nato. Sua devoção a Suzane é inabalável, e ele se entrega completamente aos desejos e planos de sua progenitora vampira. A relação entre ele e sua mãe é complexa, sendo ao mesmo tempo devoção e cumplicidade. Ele coloca os interesses de Suzane acima dos seus próprios e está disposto a fazer o que for necessário para garantir o sucesso dos planos de sua mãe.';

  texto_Natalia2: string =
    'Natália é uma jovem dona de casa que vive uma vida que parece ser tranquila à primeira vista, mas esconde uma realidade mais sombria. Casada com Marcos, um policial cuja fachada de bom homem esconde uma natureza violenta, ela enfrenta desafios significativos em seu cotidiano. As marcas de seu sofrimento são cuidadosamente ocultadas por trás de portas fechadas. Sua curiosidade com a vida das pessoas na vizinhança torna-se uma fuga, uma forma de escapar momentaneamente da dura realidade que enfrenta em casa. A relação entre Natália e Valéria cresce à medida que compartilham segredos e experiências. Enquanto Valéria encontra na dona de casa uma aliada discreta, Natália descobre um mundo além do que seus olhos humanos poderiam perceber. A dinâmica entre elas se torna benéfica para ambas, criando uma aliança improvável que se tornará crucial nos desafios que virão.';

  texto_Natalia: string =
    'Natália é uma jovem dona de casa que vive uma aparente vida tranquila, mas esconde uma realidade sombria. Casada com Marcos, ela enfrenta desafios significativos em seu cotidiano. As marcas de seu sofrimento são cuidadosamente ocultadas por trás de portas fechadas. Sua curiosidade com a vida das pessoas na vizinhança torna-se uma fuga da dura realidade que enfrenta em casa. A relação entre Natália e Valéria cresce à medida que compartilham segredos e experiências. Enquanto Valéria encontra na dona de casa uma aliada discreta, Natália descobre um mundo além do que seus olhos humanos poderiam perceber. A dinâmica entre elas se torna benéfica para ambas, criando uma aliança improvável que se tornará crucial nos desafios que virão.';

  texto_Marcos2: string =
    'Marcos é um detetive de polícia com uma reputação que contrasta fortemente com sua verdadeira natureza. Aparentando ser um policial exemplar e marido dedicado, Marcos esconde um lado obscuro que poucos conhecem. Sua habilidade em manter uma fachada convincente torna difícil para os outros suspeitarem de suas atividades fora do ambiente de trabalho. Marcos faz parte do círculo social de Daniel, sendo vizinho e membro do mesmo grupo de amigos. Sua presença aparentemente amigável e respeitável cria uma ilusão para aqueles ao seu redor. Ele mantém opiniões extremistas que se manifestam através de sua agressividade, especialmente em seu relacionamento com Natália, sua esposa.  A relação complexa entre Natália, Valéria e Marcos cria uma teia intrincada de tensão e mistério, que moldará o destino de todos os envolvidos';

  texto_Marcos: string =
    'Marcos é um detetive de polícia  que aparenta ser um policial exemplar e marido dedicado, mas esconde um lado obscuro. Sua habilidade em manter uma fachada convincente torna difícil para os outros suspeitarem de suas atividades fora do ambiente de trabalho. Marcos faz parte do círculo social de Daniel, sendo vizinho e membro do mesmo grupo de amigos. Ele mantém opiniões extremistas que se manifestam através de sua agressividade, especialmente em seu relacionamento com Natália, sua esposa. A relação complexa entre Natália, Valéria e Marcos cria uma teia de tensão, que moldará o destino de todos os envolvidos.';

  texto_Hudson: string =
    'Hudson é um vendedor de carros que trabalha na mesma concessionária que Daniel. Seu sorriso contagiante e sua personalidade amigável fazem dele um dos vendedores mais queridos pelos clientes. Hudson é o tipo de amigo que está sempre disposto a ajudar e que traz uma energia positiva para o grupo. A presença de Hudson traz um equilíbrio bem-vindo, oferecendo alívio cômico e apoio constante.';

  texto_Gustavo: string =
    'Gustavo é um jovem técnico em informática com interesse em teorias da conspiração. Ele é um indivíduo reservado que, apesar de sua habilidade técnica, muitas vezes prefere trabalhar nos bastidores. Gustavo é uma presença constante nas atividades do grupo de amigos de Daniel. Embora seja tímido, sua lealdade e amizade profunda fazem dele um componente essencial da dinâmica do grupo. ';

  texto_Cintia: string =
    'Cíntia, irmã de Hudson, é uma figura querida entre os amigos. Sua capacidade de avaliar situações com clareza e oferecer conselhos ponderados faz dela uma amiga confiável em quem os outros podem confiar. Seu lado sensato serve como um farol nos momentos de desafio, ajudando a manter a harmonia dentro do grupo.';

  texto_Mariana: string =
    'Mariana é uma enfermeira do hospital central. Ela é incrivelmente desconfiada e perspicaz. Rapidamente, suspeita de Valéria como uma potencial assassina e se torna determinada em provar isso a Daniel, que é seu interesse romântico. Além de suas suspeitas em relação a Valéria, ela também tem a consciência de que é um possível alvo da vampira. Consciente de que sua vida corre perigo, ela se esforça para proteger não apenas a si mesma, mas também aqueles ao seu redor. Sua jornada torna-se uma batalha contra as sombras que ameaçam invadir sua vida e a segurança de seu círculo de amigos.';

  texto_Daniel: string =
    'Daniel é um administrador numa loja de carros que nutre um sonho secreto de ser pintor. Sua paixão pela arte se manifesta em quadros extraordinários, mas ele hesita em seguir esse caminho, mantendo esse aspecto criativo de sua vida em segundo plano. A vida de Daniel toma uma reviravolta inesperada quando Valéria, uma vampira obscura e obsessiva, se apaixona por ele. Inicialmente uma stalker, a relação entre eles evolui quando ele se torna alvo de uma facção perigosa. Quando Valéria salva a vida de Daniel, desencadeia uma conexão única e estranha entre eles.';

  constructor() {}

  ngOnInit(): void {}
}
